from nice_types import EnumType

FILE_UPLOAD_DIR = 'exam'

VALID_EXTENSIONS = ["doc", ".pdf", ".html", ".htm", ".txt"]

EXAM_TYPE_MIDTERM = 10
EXAM_TYPE_FINAL = 20
EXAM_TYPE_QUIZ = 40
EXAM_TYPE_REVIEW = 30

EXAM_TYPE = EnumType(MIDTERM = EXAM_TYPE_MIDTERM, FINAL = EXAM_TYPE_FINAL, QUIZ = EXAM_TYPE_QUIZ, REVIEW = EXAM_TYPE_REVIEW)
EXAM_TYPE.add_descriptions(((EXAM_TYPE.MIDTERM, "Midterm"), (EXAM_TYPE.FINAL, "Final"), (EXAM_TYPE.QUIZ, "Quiz"), (EXAM_TYPE.REVIEW, "Review")))

EXAM_ABBR = EnumType(MIDTERM = EXAM_TYPE_MIDTERM, FINAL = EXAM_TYPE_FINAL, QUIZ = EXAM_TYPE_QUIZ, REVIEW = EXAM_TYPE_REVIEW)
EXAM_ABBR.add_descriptions(((EXAM_TYPE.MIDTERM, "mt"), (EXAM_TYPE.FINAL, "final"), (EXAM_TYPE.QUIZ, "quiz"), (EXAM_TYPE.REVIEW, "review")))

