from nice_types import EnumType

RSVP_TYPE_NONE = 0
RSVP_TYPE_WHOLE = 1
RSVP_TYPE_BLOCK = 2

RSVP_TYPE = EnumType(NONE = RSVP_TYPE_NONE, WHOLE = RSVP_TYPE_WHOLE, BLOCK = RSVP_TYPE_BLOCK)
RSVP_TYPE.add_descriptions(((RSVP_TYPE.NONE, 'No RSVP'), (RSVP_TYPE.WHOLE, 'RSVP Whole Event'), (RSVP_TYPE.BLOCK, 'RSVP Time Block')))

