from nice_types import EnumType


REQUEST_OBJECT_ATTR_PREFIX = '__request_'
REQUEST_OBJECT_CONFIRM_ATTR = REQUEST_OBJECT_ATTR_PREFIX+'attr__'
REQUEST_OBJECT_COMMENT_ATTR = REQUEST_OBJECT_ATTR_PREFIX+'comment__'
REQUEST_OBJECT_METAINFO_ATTR = REQUEST_OBJECT_ATTR_PREFIX+'metainfo__'

REQUEST_METAINFO_ATTR = "__object_metainfo__"



EXAM = 0
RESUME = 1 
RSVP = 2
CHALLENGE = 3

DESCRIPTIONS = ((EXAM, "Exam File"), (RESUME, "Resume"), (RSVP, "RSVP"), (CHALLENGE, "Challenge"))

REQUEST_TYPE = EnumType(EXAM = EXAM, RESUME = RESUME, RSVP = RSVP, CHALLENGE = CHALLENGE)
REQUEST_TYPE.add_descriptions(DESCRIPTIONS)
