<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/reset.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/style.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/jquery.autocomplete.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/jquery.cluetip.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/infobox.css">