<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/hkn-general.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/info.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/tutor.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/jquery.autocomplete.css">
<link rel="stylesheet" type="text/css" href="{{STATIC_PREFIX}}css/jquery.cluetip.css">
