<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-1.2.6.js" > </script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.form.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.autocomplete.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.cluetip.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.bgiframe.js"></script>
